### ISSUE TITLE
Team Emails

### ISSUE THREAD

**Issue by FarahZaqout** [FACG6/UNOPS#1]
Add your emails to the body of this issue so I can add you on the slack space.

**Comment by alaabadra** [comment]
alaabadra4@gmail.com

**Comment by ahmedisam99** [comment]
ahmedisam9922@gmail.com

**Comment by Jamalat-shamallakh** [comment]
jamallat12shamallakh@gmail.com

**Comment by Anies12** [comment]
a2nies2012@gmail.com
